routes/web.php
<?php

use Bittacora\Language\Http\Controllers\LanguageController;
use Illuminate\Support\Facades\Route;

Route::prefix('bpanel')->middleware(['web', 'auth','admin-menu'])->name('language.')->group(function(){
    Route::get('language', [LanguageController::class, 'index'])->name('index');
    Route::get('language/create', [LanguageController::class, 'create'])->name('create');
    Route::get('language/{language}', [LanguageController::class, 'show'])->name('show');
    Route::post('language/store', [LanguageController::class, 'store'])->name('store');
    Route::get('language/{language}/edit', [LanguageController::class, 'edit'])->name('edit');
    Route::put('language/{language}', [LanguageController::class, 'update'])->name('update');
    Route::delete('language/{language}', [LanguageController::class, 'destroy'])->name('destroy');
    Route::post('language/reorder', [LanguageController::class, 'reorder'])->name('reorder');
});

resources/views/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Idiomas')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120">
                <span class="text-90">{{ __('language::language.add') }}</span>
            </h4>
        </div>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('language.store')}}">

            @csrf
            @livewire('form::input-text', ['name' => 'name', 'labelText' => __('language::language.name'), 'required'=>true])
            @livewire('form::select', [
            'name' => 'locale',
            'labelText' => __('language::language.locale'),
            'required' => true,
            'allValues' => $locales
            ])
            @livewire('form::select', [
            'name' => 'region',
            'labelText' => __('language::language.region'),
            'required' => true,
            'allValues' => $regions
            ])
            @livewire('form::input-checkbox', ['name' => 'active', 'labelText' => __('language::language.active'), 'bpanelForm' => true])
            @livewire('form::input-checkbox', ['name' => 'default', 'labelText' => __('language::language.default'), 'bpanelForm' => true])

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'save'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
        </form>
    </div>
@endsection

resources/views/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Roles')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120">
                <span class="text-90">{{ __('language::language.language_editing') }}: {{$language->name}}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('language.update', $language)}}">
            @method('PUT')
            @csrf

            @livewire('form::input-text', ['name' => 'name', 'labelText' => __('language::language.name'), 'required'=>true, 'value'=>$language->name])
            @livewire('form::select', [
            'name' => 'locale',
            'labelText' => __('language::language.locale'),
            'required' => true,
            'allValues' => $locales,
            'selectedValues' => [$language->locale]
            ])
            @livewire('form::select', [
            'name' => 'region',
            'labelText' => __('language::language.region'),
            'required' => true,
            'allValues' => $regions,
            'selectedValues' => [$language->region]
            ])
            @livewire('form::input-checkbox', ['name' => 'active', 'labelText' => __('language::language.active'), 'bpanelForm' => true, 'checked' => $language->active])
            @livewire('form::input-checkbox', ['name' => 'default', 'labelText' => __('language::language.default'), 'bpanelForm' => true, 'checked' => $language->default])

            @livewire('utils::created-updated-info', ['model' => $language])

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'update'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
        </form>
    </div>
@endsection

resources/views/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@pushOnce('styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/language.css') }}">
@endpushOnce

@section('title', 'Idiomas')

@inject('category', 'Bittacora\Category\Category')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('language::language.language_list') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('language::language-datatable', [], key('language-datatable'))
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ Vite::asset('vendor/bittacora/bpanel4-panel/resources/assets/js/livewire-sortable.js') }}"></script>
@endpush

resources/views/livewire/datatable-checkbox.blade.php
<div class="form-check form-check-inline">
    <input class="form-check-input ace-switch input-sm"
           type="checkbox"
           @if($multiple) name="{{$name}}[]" @else name="{{$name}}" @endif
           id="{{$idField}}"
           wire:click="toggle({{$idField}})"
           @if($checked==1) checked @endif
    >
    @if(!is_null($labelText))
        <label class="form-check-label" for="{{$idField}}">{{ $labelText }}</label>
    @endif
</div>

resources/views/livewire/datatable-columns/actions-column.blade.php
@livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'language', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el idioma?'], key('language-buttons-'.$row->id))

resources/views/livewire/datatable-columns/active-column.blade.php
@livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-language-'.$row->id))

resources/views/livewire/datatable-columns/default-column.blade.php
@livewire('utils::datatable-default', ['fieldName' => 'default', 'model' => $row, 'value' => $row->default, 'size' => 'xxs', 'reload' => 'language.index'], key('default-language-'.$row->id))

resources/views/livewire/datatable-columns/order-column.blade.php
<div class="d-flex justify-content-center align-items-center">
        <span class="align-items-center badge bgc-purple-d1 pos-rel text-white radius-4 px-3">
            <span class="bgc-primary-tp4 opacity-5 position-tl h-100 w-100 radius-4"></span>
            <span class="pos-rel">
                {{$row->order_column}}
            </span>
        </span>
</div>

resources/views/livewire/datatable-default.blade.php
<div class="text-center">
    @if ($value==0)
        <button class="btn btn-danger btn-sm mb-1" wire:click="toggle({{$idField}})">
            <i class="fa fa-times"></i>
        </button>
    @else
        <button class="btn btn-success btn-sm mb-1" wire:click="toggle({{$idField}})">
            <i class="fa fa-check"></i>
        </button>
    @endif
</div>

resources/views/livewire/datatable-languages.blade.php
{{-- Pinta las banderas de los idiomas para crear o editar un contenido en función de las traducciones que tenga
     guardadas.  --}}
<div class="text-center">
    @foreach(\Bittacora\Language\LanguageFacade::getActives() as $language)
        @if(in_array($language->locale, Bittacora\Language\Language::getModelLanguages($model), true))
            <a href="{{ route($editRouteName, [$model, 'locale' => $language->locale, ...$additionalEditRouteParameters]) }}"><img src="{{asset('img/flags/'.$language->locale.'.png')}}"
                                                                                                alt="Editar el contenido en {{ $language->name }}"
                                                                                                title="Editar el contenido en {{ $language->name }}"></a>
        @else
            <a href="{{ route($editRouteName, [$model, 'locale' => $language->locale,...$additionalCreateRouteParameters ]) }}"><img src="{{asset('img/flags/'.$language->locale.'.png')}}" style="opacity: 0.3; filter: saturate(0);"
                                                                                                  alt="Crear el contenido en {{ $language->name }}"
                                                                                                  title="Crear el contenido en {{ $language->name }}"></a>
        @endif
    @endforeach
</div>

resources/views/livewire/language-datatable-row.blade.php
<td>
    <div class="text-center">
        {{$row->name}}
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->locale}}
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->region}}
    </div>
</td>
<td>
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-language-'.$row->id))
</td>
<td>
    @livewire('utils::datatable-default', ['fieldName' => 'default', 'model' => $row, 'value' => $row->default, 'size' => 'xxs', 'reload' => 'language.index'], key('default-language-'.$row->id))
</td>
<td>
    <div class="d-flex justify-content-center align-items-center">
        <span class="align-items-center badge bgc-purple-d1 pos-rel text-white radius-4 px-3">
            <span class="bgc-primary-tp4 opacity-5 position-tl h-100 w-100 radius-4"></span>
            <span class="pos-rel">
                {{$row->order_column}}
            </span>
        </span>
    </div>
</td>
<td>
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'language', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el idioma?'], key('language-buttons-'.$row->id))
    </div>
</td>

resources/views/partials/actions.blade.php
<div class="action-buttons">
    <a class="text-blue mx-2" href="{{route($scope.'.show',$id)}}">
        <i class="fa fa-search"></i>
    </a>
    <a class="text-success mx-2" href="{{route($scope.'.edit', $id)}}">
        <i class="fa fa-pencil"></i>
    </a>
    <form method="POST" class="d-inline mx-2"
          action="{{route($scope.'.destroy', $id)}}">
        {!!method_field('DELETE')!!}
        @csrf
        <button id="delete_button{{$id}}" type="submit" class="btn btn-primary-outline text-danger"
                @if($disabled) disabled @endif
                onclick="return confirm('¿Está seguro de querer borrar {{$message}}')">
            <i class="fa fa-trash"></i>
        </button>
    </form>
</div>

resources/views/partials/active.blade.php
<div class="text-center">
    @livewire('language-datatable-checkbox',[
    'idField' => $idField,
    'name' => $name,
    'checked' => $checked,
 ])
</div>

resources/views/partials/datatable-languages.blade.php
{{-- Pinta las banderas de los idiomas para crear o editar un contenido en función de las traducciones que tenga
     guardadas.  --}}
@foreach(Bittacora\Language\Language::getActives() as $language)
    @if(in_array($language->locale, Bittacora\Language\Language::getModelLanguages($model), true))
        <a href="{{ route($edit_route_name, [$model, 'locale' => $language->locale]) }}">
            <img src="{{asset('img/flags/'.$language->locale.'.png')}}"
                 alt="Editar el contenido en {{ $language->name }}"
                 title="Editar el contenido en {{ $language->name }}">
        </a>
    @else
        <a href="{{ route($edit_route_name, [$model, 'locale' => $language->locale]) }}"><img src="{{asset('img/flags/'.$language->locale.'.png')}}" style="opacity: 0.3; filter: saturate(0);"
             alt="Crear el contenido en {{ $language->name }}"
             title="Crear el contenido en {{ $language->name }}"></a>
    @endif
@endforeach

resources/views/partials/default.blade.php
<div class="text-center">
    @livewire('language-datatable-default',[
    'idField' => $idField,
    'name' => $name,
    'value' => $value,
 ])
</div>

resources/views/partials/form-languages.blade.php
<style>
    .content-language-icon {
        position: relative;
    }

    .content-language-icon::before {
        display: none;

        font-family: "Font Awesome 5 Pro";
        font-weight: 900;
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        display: inline-block;
        font-style: normal;
        font-variant: normal;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        text-align: center;
        color: white;
        text-shadow: 1px 1px black, -1px 1px black, -1px -1px black, 1px -1px black;
    }

    .content-language-icon-edit::before {
        content: "\f303";
    }

    .content-language-icon-create::before {
        content: "\f067";
    }
</style>

{{-- Pinta las banderas de los idiomas para crear o editar un contenido en función de las traducciones que tenga
     guardadas.  --}}

<div class="d-flex justify-content-end">
    @foreach($languages as $language)
        @if(in_array($language->locale, Bittacora\Language\Language::getModelLanguages($model), true))
            {{-- El contenido ya está creado en este idioma --}}
            <a href="{{ route($edit_route_name, [
                'model' => $model,
                'locale' => $language->locale,
                ...($additionalEditRouteParameters ?? [])
                ]) }}" class="ml-1 content-language-icon content-language-icon-edit">
                <img src="{{asset('img/flags/'.$language->locale.'.png')}}"
                     alt="Editar el contenido en {{ $language->name }}"
                     title="Editar el contenido en {{ $language->name }}"
                     @if($language->locale !== $currentLanguage) style="opacity: 0.3; filter: saturate(0);" @endif>
            </a>
        @else
            {{-- El contenido no existe en este idioma --}}
            <a href="{{ route($edit_route_name, [
                'model' => $model,
                'locale' => $language->locale,
                ...($additionalEditRouteParameters ?? [])
                ]) }}" class="ml-1 content-language-icon content-language-icon-create">
                <img src="{{asset('img/flags/'.$language->locale.'.png')}}"
                     alt="Crear el contenido en {{ $language->name }}"
                     title="Crear el contenido en {{ $language->name }}"
                     @if($language->locale !== $currentLanguage) style="opacity: 0.3; filter: saturate(0);" @endif>
            </a>
        @endif
    @endforeach
</div>

resources/views/show.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Roles')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 mb-5">
            <h4 class="text-120">
                <span class="text-90">{{ __('language::language.show') }}</span>
            </h4>
        </div>

            @livewire('form::input-text', ['name' => 'name', 'labelText' => __('language::language.name'), 'required'=>true,'disabled' => true, 'value'=>$language->name])
            @livewire('form::input-text', ['name' => 'locale', 'labelText' => __('language::language.locale'), 'required'=>true,'disabled' => true,
        'value'=>$language->locale])
            @livewire('form::input-text', ['name' => 'locale', 'labelText' => __('language::language.region'), 'required'=>true,'disabled' => true,
        'value'=>$language->region])

            @livewire('form::input-checkbox', ['name' => 'active', 'labelText' => __('language::language.active'), 'bpanelForm' => true,'disabled' => true, 'checked' =>
        $language->active])
            @livewire('form::input-checkbox', ['name' => 'default', 'labelText' => __('language::language.default'), 'bpanelForm' => true,'disabled' => true, 'checked' =>
        $language->default])

        @livewire('utils::created-updated-info', ['model' => $language])

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                <a class="btn btn-success btn-bold px-4 mx-2" href="{{route('language.index')}}">
                    <i class="fa fa-list mr-1" aria-hidden="true"></i>
                    &nbsp;Listado
                </a>
            </div>
        </form>
    </div>
@endsection